# Generated by Django 4.0.3 on 2022-05-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_payment_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='task',
            new_name='Task',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='pay_name',
        ),
        migrations.AlterField(
            model_name='payment',
            name='cheque_no',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
