# Generated by Django 4.0.3 on 2022-05-19 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_task_employee_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.task'),
        ),
    ]
