# Generated by Django 4.0.3 on 2022-05-23 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_payment_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='pstart_date',
            new_name='pend_date',
        ),
    ]
