# Generated by Django 4.0.3 on 2022-06-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_pstart_date_project_pend_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pbudget',
            field=models.FloatField(null=True, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pend_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.BooleanField(default=False, verbose_name='Project Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ptotalcost',
            field=models.FloatField(null=True, verbose_name='Total Cost'),
        ),
    ]
