# Generated by Django 4.0.3 on 2022-06-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_task_description_alter_task_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='pbudget',
            field=models.PositiveIntegerField(null=True, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ptotalcost',
            field=models.PositiveIntegerField(null=True, verbose_name='Total Cost'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_cost',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
