# Generated by Django 4.0.3 on 2022-06-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_payment_pay_amount_alter_project_pbudget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_hour',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.BooleanField(default=False, verbose_name='Completed?'),
        ),
    ]
